### ISSUE TITLE
Logic for Win/Loss Conditions

### ISSUE THREAD

**Issue by stynan27** [stynan27/PazaakApp#16]
Win Conditions:
- Outscore, if both the Player and Opponent STAND the one with a score closer to 20 wins the round.
- Bust, If a Player/Opponent ENDs or STANDs with a score over 20 they "bust", the opposite player will then win the round.
- Filling the table, if a Player/Opponent fills all 9 card slots on a table without "busting", that player wins the round. 
~- Tiebreaker card, if a Player/Opponent is tied after playing a "tiebreaker" card, the player who placed the card wins the round.~ <- later

Ties: No one wins the round.

### TODOS:
- [x] Create a component for displaying match status messages
- [x] Conditionally display match messages based on the win/loss conditions
- [x] Update Player/Opponent round scores based on the win/loss conditions
- [x] If a Player/Opponent has 3 rounds won, display a match status dialogue naming the winner. Upon exiting the dialogue return the Player/Opponent to the Main Menu.

**Comment by stynan27** [comment]
dialog types: win, loss, forfeit.

Depending on if either the player or opponent has a roundsWon of 3, then display win/loss of match instead of set.

**Comment by stynan27** [comment]
I'd like to make the win condition calculation part of existing store modules.

**Comment by stynan27** [comment]
Win/loss conditions have been established by APP_DETERMINE_ROUND_WINNER (by round) and localized dialog check using the player/opponent rounds won attribute for game win/loss.

Will refine when these triggers occur in a new issue.
